use RUTVIK11 ;
SELECT * FROM STUDENT;

DROP TABLE STUDENT;
CREATE TABLE COURSE
(
STUDENT_ROLLNO INT PRIMARY KEY,
STUDENT_NAME VARCHAR(20),
STUDENT_ADD VARCHAR(20),
GENDER VARCHAR(5),
STUDENT_AGE INT
);
SELECT * FROM COURSE;

SELECT * FROM COURSE
WHERE STUDENT_ADD = 'SIDHPUR' or STUDENT_ADD = 'MAHESANA';

SELECT * FROM COURSE 
ORDER BY STUDENT_NAME ASC ; 

SELECT * FROM COURSE 
ORDER BY STUDENT_NAME DESC ; 

INSERT INTO COURSE (STUDENT_ROLLNO, STUDENT_NAME, STUDENT_ADD, GENDER, STUDENT_AGE)
VALUES (7,'RAMESH','PATAN','M',18);

INSERT INTO COURSE 
VALUES (8,'MAHESH','VADODRA','M',19);

SELECT * FROM COURSE;

SELECT GENDER
FROM COURSE
WHERE GENDER IS NULL ;

UPDATE COURSE
SET STUDENT_AGE = 25
WHERE STUDENT_ROLLNO;

SELECT * FROM COURSE;

DELETE FROM COURSE 
WHERE STUDENT_ROLLNO = 6;

SELECT STUDENT_ROLLNO
FROM COURSE 
WHERE STUDENT_ROLLNO
LIMIT 3;

SELECT * FROM COURSE
LIMIT 4;


SELECT * FROM COURSE;
