USE DT1;

SELECT * FROM ZOMATO
CROSS JOIN OLA;	

SELECT COUNT(Z_ID) , Z_CITY FROM ZOMATO
GROUP BY  Z_CITY ;

SELECT COUNT(Z_ID) , Z_CITY 
FROM ZOMATO
GROUP BY  Z_CITY 
HAVING COUNT(Z_ID) >  1 ;

SELECT Z_ID FROM ZOMATO
WHERE Z_ID = ANY (SELECT O_ID FROM OLA 
                  WHERE O_OLA = 10);
                  
SELECT * FROM ZOMATO
WHERE Z_ID = ANY (SELECT O_NAME FROM OLA WHERE O_ID = "110" );    

SELECT Z_ID , Z_NAME ,
CASE 
     WHEN Z_ID > 5 THEN "ABOVE 10 "
    
     WHEN Z_ID = 10 THEN "ONLY 10 "
    
    ELSE "NOT FOUND "
END DESCRIBE_A

FROM ZOMATO;
