CREATE DATABASE RK ;
USE RK ;
CREATE TABLE STUDENT 
(
R_ID INT PRIMARY KEY,
R_NAME VARCHAR (45),
R_LNAME VARCHAR (23)
);

SELECT * FROM RK.STUDENT;

CREATE TABLE COURSE SELECT * FROM STUDENT ;

truncate TABLE STUDENT ;

DROP TABLE STUDENT ;
